events {}

http {

    # zone de rate limit
    limit_req_zone $binary_remote_addr zone=ollama_limit:10m rate=5r/s;

    server {
        listen 80;

        location / {

            # rate limiting
            limit_req zone=ollama_limit burst=10 nodelay;

            # token
            set $token "b8b2c5e4c9a64c4a9c7f3c2d7f0a6b1e4f9d2c6a8b7e5f3d1c9a0b6e2d4f7a8c";

            if ($http_authorization != "Bearer $token") {
                return 403;
            }

            proxy_pass http://ollama:11434;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}